[profile_name]
type = s3
provider = Ceph
env_auth = False
access_key_id = 
secret_access_key = 
endpoint = s3.be.du.cesnet.cz
acl = private
no_check_bucket = true

[profile_name_enc]
type = crypt
remote = profile_name:bucket_name
filename_encryption = Standard
directory_name_encryption = true
password = 
password2 = 

